// Code generated by "stringer -type TypeCategory registry.go"; DO NOT EDIT.

package def

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CatNone-0]
	_ = x[CatGeneric-1]
	_ = x[CatPrimitive-2]
	_ = x[CatInclude-3]
	_ = x[CatBasetype-4]
	_ = x[CatStatic-5]
	_ = x[CatPointer-6]
	_ = x[CatHandle-7]
	_ = x[CatEnum-8]
	_ = x[CatBitmask-9]
	_ = x[CatStruct-10]
	_ = x[CatCommand-11]
	_ = x[CatMaximum-12]
}

const _TypeCategory_name = "CatNoneCatGenericCatPrimitiveCatIncludeCatBasetypeCatStaticCatPointerCatHandleCatEnumCatBitmaskCatStructCatCommandCatMaximum"

var _TypeCategory_index = [...]uint8{0, 7, 17, 29, 39, 50, 59, 69, 78, 85, 95, 104, 114, 124}

func (i TypeCategory) String() string {
	if i < 0 || i >= TypeCategory(len(_TypeCategory_index)-1) {
		return "TypeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeCategory_name[_TypeCategory_index[i]:_TypeCategory_index[i+1]]
}
