// Code generated by "stringer -type TypeCategory"; DO NOT EDIT.

package def

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CatNone-0]
	_ = x[CatExten-1]
	_ = x[CatDefine-2]
	_ = x[CatInclude-3]
	_ = x[CatExternal-4]
	_ = x[CatHandle-5]
	_ = x[CatBasetype-6]
	_ = x[CatEnum-7]
	_ = x[CatBitmask-8]
	_ = x[CatStruct-9]
	_ = x[CatUnion-10]
	_ = x[CatPointer-11]
	_ = x[CatArray-12]
	_ = x[CatCommand-13]
	_ = x[CatMaximum-14]
}

const _TypeCategory_name = "CatNoneCatExtenCatDefineCatIncludeCatExternalCatHandleCatBasetypeCatEnumCatBitmaskCatStructCatUnionCatPointerCatArrayCatCommandCatMaximum"

var _TypeCategory_index = [...]uint8{0, 7, 15, 24, 34, 45, 54, 65, 72, 82, 91, 99, 109, 117, 127, 137}

func (i TypeCategory) String() string {
	if i < 0 || i >= TypeCategory(len(_TypeCategory_index)-1) {
		return "TypeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeCategory_name[_TypeCategory_index[i]:_TypeCategory_index[i+1]]
}
