// Code generated by "stringer -type TypeCategory"; DO NOT EDIT.

package def

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CatNone-0]
	_ = x[CatDefine-1]
	_ = x[CatInclude-2]
	_ = x[CatExternal-3]
	_ = x[CatHandle-4]
	_ = x[CatBasetype-5]
	_ = x[CatBitmask-6]
	_ = x[CatEnum-7]
	_ = x[CatStruct-8]
	_ = x[CatUnion-9]
	_ = x[CatPointer-10]
	_ = x[CatArray-11]
	_ = x[CatCommand-12]
	_ = x[CatMaximum-13]
}

const _TypeCategory_name = "CatNoneCatDefineCatIncludeCatExternalCatHandleCatBasetypeCatBitmaskCatEnumCatStructCatUnionCatPointerCatArrayCatCommandCatMaximum"

var _TypeCategory_index = [...]uint8{0, 7, 16, 26, 37, 46, 57, 67, 74, 83, 91, 101, 109, 119, 129}

func (i TypeCategory) String() string {
	if i < 0 || i >= TypeCategory(len(_TypeCategory_index)-1) {
		return "TypeCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeCategory_name[_TypeCategory_index[i]:_TypeCategory_index[i+1]]
}
